# Project: task
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o node.o
LINKOBJ  = main.o node.o
LIBS     = -L"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib" -L"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/x86_64-w64-mingw32/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/x86_64-w64-mingw32/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = task.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c11
CFLAGS   = $(INCS) -g3 -std=c11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

node.o: node.c
	$(CC) -c node.c -o node.o $(CFLAGS)
